version: 2.1

commands:
  test-nodejs:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: Pull Submodules
          command: git submodule update --init
      - restore_cache:
          name: "Restoring Cache: npm cache"
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
      - restore_cache:
          name: "Restoring Cache: gradle wrapper"
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Compile
          command: npm run build
      - run:
          name: Test
          command: npm test
      - save-npm-cache
      - save_cache:
          name: "Restoring Cache: gradle wrapper"
          paths:
            - ~/.gradle/wrapper/
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  save-npm-cache:
    steps:
      - save_cache:
          name: "Saving Cache: npm cache"
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/_cacache

jobs:
  node-v8:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - test-nodejs
  node-v10:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - test-nodejs
  node-v11:
    docker:
      - image: circleci/node:11-browsers
    steps:
      - test-nodejs

workflows:
  node-multi-build:
    jobs:
      - node-v8
      - node-v10
      - node-v11
